// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dixtwbcdprbhiwhtgdfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeHR3YmNkcHJiaGl3aHRnZGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MzkwODEsImV4cCI6MjA3ODQxNTA4MX0.vDv2v2_G2_9pBMlTh2It6kIO4DDQV_8C3d3j7RkVwCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
